version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.0.0
jobs:
  nodejs_api:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - run: export TIMESTAMP=$(date +%s)
      - run: export FILENAME="s3://node-cicd-asg-s3/NodeJS-Server_"$TIMESTAMP".zip"
      - run: |
          aws deploy push \
          --application-name nishant-asg-cicd \
          --description "from cicleCI to S3 with love" \
          --ignore-hidden-files \
          --s3-location $FILENAME \
          --source ./

workflows:
  asg_ec2_workflow:
    jobs:
      - nodejs_api:
          context: AWS
